spring.application.name=backend

server.port=${PORT:8080}

spring.datasource.url=jdbc:postgresql://aws-1-us-east-2.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.uuybnwyryrezzauktcuf
spring.datasource.password=rM16oOZn8I128gos
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.connection-timeout=30000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

aws.accessKeyId=${AWS_ACCESS_KEY_ID}
aws.secretKey=${AWS_SECRET_ACCESS_KEY}
aws.region=${AWS_REGION}
aws.s3.bucketName=${AWS_BUCKET_NAME}

github.client.id=Ov23liBv9hjUZASAX3B3
github.client.secret=bcfa5a7e3cbb18a5a6842fa0190398b8d7ca026a
github.redirect.uri=http://localhost:8081/redirect

github.mobile.client.id=Ov23liSeQY3GydJdm9y1
github.mobile.client.secret=8f8e9b925adb81d5a076bcff91c9ef2f2b1798f1
github.mobile.redirect.uri=exp://192.168.50.186:8081

# Use a local in-memory database for tests.
# Comment out the Supabase config above when running tests,
# and enable the test config below instead.

#spring.datasource.url=jdbc:h2:mem:testdb;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#spring.jpa.hibernate.ddl-auto=create-drop
## remove this line:
## spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
